# AX7203 / A7203x board constraints.
# Pin assignments follow board_manifest_ax7203.md and the referenced AX7203 manual.

# 200 MHz system clock: SYS_CLK_P/SYS_CLK_N on R4/T4, Bank 34.
set_property -dict {PACKAGE_PIN R4 IOSTANDARD DIFF_SSTL15} [get_ports {chipset_clk_osc_p}]
set_property -dict {PACKAGE_PIN T4 IOSTANDARD DIFF_SSTL15} [get_ports {chipset_clk_osc_n}]
create_clock -period 5.000 -name chipset_clk_osc_p [get_ports chipset_clk_osc_p]
set_property CLOCK_DEDICATED_ROUTE BACKBONE [get_nets chipset/clk_mmcm/inst/clk_in1_clk_mmcm]

# Active-low reset key on the core board.
set_property -dict {PACKAGE_PIN T6 IOSTANDARD LVCMOS15 PULLUP true} [get_ports {sys_rst_n}]

# USB-UART CP2102GM, 115200 8N1 at software level.
# UART1_RXD (P20) = FPGA receives here, UART1_TXD (N15) = FPGA transmits here
set_property -dict {PACKAGE_PIN P20 IOSTANDARD LVCMOS33} [get_ports {uart_rx}]
set_property -dict {PACKAGE_PIN N15 IOSTANDARD LVCMOS33} [get_ports {uart_tx}]

# MicroSD card slot, SD mode.
set_property -dict {PACKAGE_PIN AB12 IOSTANDARD LVCMOS33 DRIVE 16 SLEW FAST} [get_ports {sd_clk_out}]
set_property -dict {PACKAGE_PIN AB11 IOSTANDARD LVCMOS33} [get_ports {sd_cmd}]
set_property -dict {PACKAGE_PIN F14  IOSTANDARD LVCMOS33} [get_ports {sd_cd}]
set_property -dict {PACKAGE_PIN AA13 IOSTANDARD LVCMOS33} [get_ports {sd_dat[0]}]
set_property -dict {PACKAGE_PIN AB13 IOSTANDARD LVCMOS33} [get_ports {sd_dat[1]}]
set_property -dict {PACKAGE_PIN Y13  IOSTANDARD LVCMOS33} [get_ports {sd_dat[2]}]
set_property -dict {PACKAGE_PIN AA14 IOSTANDARD LVCMOS33} [get_ports {sd_dat[3]}]

# User LEDs: core-board LED plus four carrier-board LEDs.
set_property -dict {PACKAGE_PIN W5  IOSTANDARD LVCMOS15} [get_ports {leds[0]}]
set_property -dict {PACKAGE_PIN B13 IOSTANDARD LVCMOS33} [get_ports {leds[1]}]
set_property -dict {PACKAGE_PIN C13 IOSTANDARD LVCMOS33} [get_ports {leds[2]}]
set_property -dict {PACKAGE_PIN D14 IOSTANDARD LVCMOS33} [get_ports {leds[3]}]
set_property -dict {PACKAGE_PIN D15 IOSTANDARD LVCMOS33} [get_ports {leds[4]}]

# DDR3 SDRAM, 2x MT41J256M16HA-125, 32-bit bus, Banks 34/35.
set_property -dict {PACKAGE_PIN AA4 IOSTANDARD SSTL15} [get_ports {ddr_addr[0]}]
set_property -dict {PACKAGE_PIN AB2 IOSTANDARD SSTL15} [get_ports {ddr_addr[1]}]
set_property -dict {PACKAGE_PIN AA5 IOSTANDARD SSTL15} [get_ports {ddr_addr[2]}]
set_property -dict {PACKAGE_PIN AB5 IOSTANDARD SSTL15} [get_ports {ddr_addr[3]}]
set_property -dict {PACKAGE_PIN AB1 IOSTANDARD SSTL15} [get_ports {ddr_addr[4]}]
set_property -dict {PACKAGE_PIN U3  IOSTANDARD SSTL15} [get_ports {ddr_addr[5]}]
set_property -dict {PACKAGE_PIN W1  IOSTANDARD SSTL15} [get_ports {ddr_addr[6]}]
set_property -dict {PACKAGE_PIN T1  IOSTANDARD SSTL15} [get_ports {ddr_addr[7]}]
set_property -dict {PACKAGE_PIN V2  IOSTANDARD SSTL15} [get_ports {ddr_addr[8]}]
set_property -dict {PACKAGE_PIN U2  IOSTANDARD SSTL15} [get_ports {ddr_addr[9]}]
set_property -dict {PACKAGE_PIN Y1  IOSTANDARD SSTL15} [get_ports {ddr_addr[10]}]
set_property -dict {PACKAGE_PIN W2  IOSTANDARD SSTL15} [get_ports {ddr_addr[11]}]
set_property -dict {PACKAGE_PIN Y2  IOSTANDARD SSTL15} [get_ports {ddr_addr[12]}]
set_property -dict {PACKAGE_PIN U1  IOSTANDARD SSTL15} [get_ports {ddr_addr[13]}]
set_property -dict {PACKAGE_PIN V3  IOSTANDARD SSTL15} [get_ports {ddr_addr[14]}]
set_property -dict {PACKAGE_PIN AA3 IOSTANDARD SSTL15} [get_ports {ddr_ba[0]}]
set_property -dict {PACKAGE_PIN Y3  IOSTANDARD SSTL15} [get_ports {ddr_ba[1]}]
set_property -dict {PACKAGE_PIN Y4  IOSTANDARD SSTL15} [get_ports {ddr_ba[2]}]
set_property -dict {PACKAGE_PIN AB3 IOSTANDARD SSTL15} [get_ports {ddr_cs_n[0]}]
set_property -dict {PACKAGE_PIN V4  IOSTANDARD SSTL15} [get_ports {ddr_ras_n}]
set_property -dict {PACKAGE_PIN W4  IOSTANDARD SSTL15} [get_ports {ddr_cas_n}]
set_property -dict {PACKAGE_PIN AA1 IOSTANDARD SSTL15} [get_ports {ddr_we_n}]
set_property -dict {PACKAGE_PIN U5  IOSTANDARD SSTL15} [get_ports {ddr_odt[0]}]
set_property -dict {PACKAGE_PIN W6  IOSTANDARD LVCMOS15} [get_ports {ddr_reset_n}]
set_property -dict {PACKAGE_PIN R3  IOSTANDARD DIFF_SSTL15} [get_ports {ddr_ck_p[0]}]
set_property -dict {PACKAGE_PIN R2  IOSTANDARD DIFF_SSTL15} [get_ports {ddr_ck_n[0]}]
set_property -dict {PACKAGE_PIN T5  IOSTANDARD SSTL15} [get_ports {ddr_cke[0]}]

set_property -dict {PACKAGE_PIN C2 IOSTANDARD SSTL15} [get_ports {ddr_dq[0]}]
set_property -dict {PACKAGE_PIN G1 IOSTANDARD SSTL15} [get_ports {ddr_dq[1]}]
set_property -dict {PACKAGE_PIN A1 IOSTANDARD SSTL15} [get_ports {ddr_dq[2]}]
set_property -dict {PACKAGE_PIN F3 IOSTANDARD SSTL15} [get_ports {ddr_dq[3]}]
set_property -dict {PACKAGE_PIN B2 IOSTANDARD SSTL15} [get_ports {ddr_dq[4]}]
set_property -dict {PACKAGE_PIN F1 IOSTANDARD SSTL15} [get_ports {ddr_dq[5]}]
set_property -dict {PACKAGE_PIN B1 IOSTANDARD SSTL15} [get_ports {ddr_dq[6]}]
set_property -dict {PACKAGE_PIN E2 IOSTANDARD SSTL15} [get_ports {ddr_dq[7]}]
set_property -dict {PACKAGE_PIN H3 IOSTANDARD SSTL15} [get_ports {ddr_dq[8]}]
set_property -dict {PACKAGE_PIN G3 IOSTANDARD SSTL15} [get_ports {ddr_dq[9]}]
set_property -dict {PACKAGE_PIN H2 IOSTANDARD SSTL15} [get_ports {ddr_dq[10]}]
set_property -dict {PACKAGE_PIN H5 IOSTANDARD SSTL15} [get_ports {ddr_dq[11]}]
set_property -dict {PACKAGE_PIN J1 IOSTANDARD SSTL15} [get_ports {ddr_dq[12]}]
set_property -dict {PACKAGE_PIN J5 IOSTANDARD SSTL15} [get_ports {ddr_dq[13]}]
set_property -dict {PACKAGE_PIN K1 IOSTANDARD SSTL15} [get_ports {ddr_dq[14]}]
set_property -dict {PACKAGE_PIN H4 IOSTANDARD SSTL15} [get_ports {ddr_dq[15]}]
set_property -dict {PACKAGE_PIN L4 IOSTANDARD SSTL15} [get_ports {ddr_dq[16]}]
set_property -dict {PACKAGE_PIN M3 IOSTANDARD SSTL15} [get_ports {ddr_dq[17]}]
set_property -dict {PACKAGE_PIN L3 IOSTANDARD SSTL15} [get_ports {ddr_dq[18]}]
set_property -dict {PACKAGE_PIN J6 IOSTANDARD SSTL15} [get_ports {ddr_dq[19]}]
set_property -dict {PACKAGE_PIN K3 IOSTANDARD SSTL15} [get_ports {ddr_dq[20]}]
set_property -dict {PACKAGE_PIN K6 IOSTANDARD SSTL15} [get_ports {ddr_dq[21]}]
set_property -dict {PACKAGE_PIN J4 IOSTANDARD SSTL15} [get_ports {ddr_dq[22]}]
set_property -dict {PACKAGE_PIN L5 IOSTANDARD SSTL15} [get_ports {ddr_dq[23]}]
set_property -dict {PACKAGE_PIN P1 IOSTANDARD SSTL15} [get_ports {ddr_dq[24]}]
set_property -dict {PACKAGE_PIN N4 IOSTANDARD SSTL15} [get_ports {ddr_dq[25]}]
set_property -dict {PACKAGE_PIN R1 IOSTANDARD SSTL15} [get_ports {ddr_dq[26]}]
set_property -dict {PACKAGE_PIN N2 IOSTANDARD SSTL15} [get_ports {ddr_dq[27]}]
set_property -dict {PACKAGE_PIN M6 IOSTANDARD SSTL15} [get_ports {ddr_dq[28]}]
set_property -dict {PACKAGE_PIN N5 IOSTANDARD SSTL15} [get_ports {ddr_dq[29]}]
set_property -dict {PACKAGE_PIN P6 IOSTANDARD SSTL15} [get_ports {ddr_dq[30]}]
set_property -dict {PACKAGE_PIN P2 IOSTANDARD SSTL15} [get_ports {ddr_dq[31]}]

set_property -dict {PACKAGE_PIN D2 IOSTANDARD SSTL15} [get_ports {ddr_dm[0]}]
set_property -dict {PACKAGE_PIN G2 IOSTANDARD SSTL15} [get_ports {ddr_dm[1]}]
set_property -dict {PACKAGE_PIN M2 IOSTANDARD SSTL15} [get_ports {ddr_dm[2]}]
set_property -dict {PACKAGE_PIN M5 IOSTANDARD SSTL15} [get_ports {ddr_dm[3]}]
set_property -dict {PACKAGE_PIN E1 IOSTANDARD DIFF_SSTL15} [get_ports {ddr_dqs_p[0]}]
set_property -dict {PACKAGE_PIN D1 IOSTANDARD DIFF_SSTL15} [get_ports {ddr_dqs_n[0]}]
set_property -dict {PACKAGE_PIN K2 IOSTANDARD DIFF_SSTL15} [get_ports {ddr_dqs_p[1]}]
set_property -dict {PACKAGE_PIN J2 IOSTANDARD DIFF_SSTL15} [get_ports {ddr_dqs_n[1]}]
set_property -dict {PACKAGE_PIN M1 IOSTANDARD DIFF_SSTL15} [get_ports {ddr_dqs_p[2]}]
set_property -dict {PACKAGE_PIN L1 IOSTANDARD DIFF_SSTL15} [get_ports {ddr_dqs_n[2]}]
set_property -dict {PACKAGE_PIN P5 IOSTANDARD DIFF_SSTL15} [get_ports {ddr_dqs_p[3]}]
set_property -dict {PACKAGE_PIN P4 IOSTANDARD DIFF_SSTL15} [get_ports {ddr_dqs_n[3]}]

# Cross-domain timing exceptions used by the existing OpenPiton FPGA flow.
set_false_path -to [get_cells -quiet -hierarchical *afifo_ui_rst_r*]
set_false_path -to [get_cells -quiet -hierarchical *ui_clk_sync_rst_r*]
set_false_path -to [get_cells -quiet -hierarchical *ui_clk_syn_rst_delayed*]
set_false_path -to [get_cells -quiet -hierarchical *init_calib_complete_f*]
set_false_path -to [get_cells -quiet -hierarchical *chipset_rst_n*]
set_false_path -from [get_clocks -quiet chipset_clk_clk_mmcm] -to [get_clocks -quiet net_axi_clk_clk_mmcm]
set_false_path -from [get_clocks -quiet net_axi_clk_clk_mmcm] -to [get_clocks -quiet chipset_clk_clk_mmcm]

# SD Card Constraints for 25MHz
create_generated_clock -name sd_fast_clk -source [get_pins chipset/clk_mmcm/sd_sys_clk] -divide_by 2 [get_pins chipset/chipset_impl/piton_sd_top/sdc_controller/clock_divider0/fast_clk_reg/Q]
create_generated_clock -name sd_slow_clk -source [get_pins chipset/clk_mmcm/sd_sys_clk] -divide_by 200 [get_pins chipset/chipset_impl/piton_sd_top/sdc_controller/clock_divider0/slow_clk_reg/Q]
create_generated_clock -name sd_clk_out   -source [get_pins chipset/sd_clk_oddr/C] -divide_by 1 -add -master_clock sd_fast_clk [get_ports sd_clk_out]
create_generated_clock -name sd_clk_out_1 -source [get_pins chipset/sd_clk_oddr/C] -divide_by 1 -add -master_clock sd_slow_clk [get_ports sd_clk_out]

set_clock_uncertainty 0.500 [get_clocks sd_clk_out]
set_clock_uncertainty 0.500 [get_clocks sd_clk_out_1]

set_output_delay -clock [get_clocks sd_clk_out] -min -add_delay -6.000 [get_ports {sd_dat[*]}]
set_output_delay -clock [get_clocks sd_clk_out] -min -add_delay -6.000 [get_ports sd_cmd]
set_output_delay -clock [get_clocks sd_clk_out] -max -add_delay 8.000 [get_ports {sd_dat[*]}]
set_output_delay -clock [get_clocks sd_clk_out] -max -add_delay 8.000 [get_ports sd_cmd]
set_output_delay -clock [get_clocks sd_clk_out_1] -min -add_delay -8.000 [get_ports {sd_dat[*]}]
set_output_delay -clock [get_clocks sd_clk_out_1] -min -add_delay -8.000 [get_ports sd_cmd]
set_output_delay -clock [get_clocks sd_clk_out_1] -max -add_delay 8.000 [get_ports {sd_dat[*]}]
set_output_delay -clock [get_clocks sd_clk_out_1] -max -add_delay 8.000 [get_ports sd_cmd]

set_input_delay -clock [get_clocks sd_clk_out] -clock_fall -max -add_delay 14.000 [get_ports {sd_dat[*]}]
set_input_delay -clock [get_clocks sd_clk_out] -clock_fall -max -add_delay 14.000 [get_ports sd_cmd]
set_input_delay -clock [get_clocks sd_clk_out] -clock_fall -min -add_delay -14.000 [get_ports {sd_dat[*]}]
set_input_delay -clock [get_clocks sd_clk_out] -clock_fall -min -add_delay -14.000 [get_ports sd_cmd]
set_input_delay -clock [get_clocks sd_clk_out_1] -clock_fall -max -add_delay 14.000 [get_ports {sd_dat[*]}]
set_input_delay -clock [get_clocks sd_clk_out_1] -clock_fall -max -add_delay 14.000 [get_ports sd_cmd]
set_input_delay -clock [get_clocks sd_clk_out_1] -clock_fall -min -add_delay -14.000 [get_ports {sd_dat[*]}]
set_input_delay -clock [get_clocks sd_clk_out_1] -clock_fall -min -add_delay -14.000 [get_ports sd_cmd]

set_clock_groups -physically_exclusive -group [get_clocks -include_generated_clocks sd_clk_out] -group [get_clocks -include_generated_clocks sd_clk_out_1]
set_clock_groups -logically_exclusive -group [get_clocks -include_generated_clocks sd_fast_clk] -group [get_clocks -include_generated_clocks sd_slow_clk]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks chipset_clk_clk_mmcm] -group [get_clocks -filter { NAME =~  "*sd*" }]

set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
