# p3_build75_insert_debug.tcl -- Post-synthesis hook for the Build 75
# single-hart PC/L1.5 diagnostic ILA.

if {![info exists project_dir] || ![info exists project_name]} {
    puts "ERROR: Build 75 hook requires project_dir and project_name"
    exit 1
}

set build75_l15_base \
    "u_openpiton/system_inst/chip/tile0/l15/l15/pipeline"
set build75_scoreboard_base \
    "u_openpiton/system_inst/chip/tile0/g_ariane_core.core/ariane/i_cva6/issue_stage_i/i_scoreboard/commit_instr_id_commit\[0\]"
set build75_cva6_base \
    "u_openpiton/system_inst/chip/tile0/g_ariane_core.core/ariane/i_cva6"

proc p3_build75_bus_nets {base width} {
    set nets {}
    for {set bit 0} {$bit < $width} {incr bit} {
        set name "${base}\[${bit}\]"
        set matches [get_nets -quiet [list $name]]
        if {[llength $matches] != 1} {
            error "Build 75 expected one net ${name}, found [llength $matches]"
        }
        lappend nets [lindex $matches 0]
    }
    return $nets
}

proc p3_build75_scalar_net {name} {
    set matches [get_nets -quiet [list $name]]
    if {[llength $matches] != 1} {
        error "Build 75 expected one net ${name}, found [llength $matches]"
    }
    return [lindex $matches 0]
}

proc p3_build75_xdc_net_list {base width} {
    set names {}
    for {set bit 0} {$bit < $width} {incr bit} {
        lappend names "{${base}\[${bit}\]}"
    }
    return [join $names " "]
}

proc p3_build75_write_probe {fh port base width trigger} {
    if {$port ne "probe0"} {
        puts $fh "create_debug_port u_ila_build75 probe"
    }
    puts $fh "set_property port_width ${width} \[get_debug_ports u_ila_build75/${port}\]"
    if {$trigger} {
        puts $fh "set_property PROBE_TYPE DATA_AND_TRIGGER \[get_debug_ports u_ila_build75/${port}\]"
    } else {
        puts $fh "set_property PROBE_TYPE DATA \[get_debug_ports u_ila_build75/${port}\]"
    }
    if {$width == 1} {
        puts $fh "connect_debug_port u_ila_build75/${port} \[get_nets \[list {${base}}\]\]"
    } else {
        puts $fh "connect_debug_port u_ila_build75/${port} \[get_nets \[list [p3_build75_xdc_net_list $base $width]\]\]"
    }
}

open_run synth_1

set req_base "${build75_l15_base}/p3_build75_l15_req_bus"
set stall_base "${build75_l15_base}/p3_build75_l15_stall_bus"
set count_base "${build75_l15_base}/p3_build75_noack_count"
set trigger_name "${build75_l15_base}/p3_build75_noack_trigger"
set pc_base "${build75_scoreboard_base}\[pc\]"
set fu_base "${build75_scoreboard_base}\[fu\]"
set op_base "${build75_scoreboard_base}\[op\]"
set valid_name "${build75_scoreboard_base}\[valid\]"
set commit_ack_name "${build75_cva6_base}/issue_stage_i/i_scoreboard/commit_ack\[0\]"
set lsu_ready_name "${build75_cva6_base}/lsu_commit_ready_ex_commit"
set lsu_commit_name "${build75_cva6_base}/lsu_commit_commit_ex"

# Fail before implementation if synthesis renamed, optimized, or duplicated a
# probe. This avoids publishing an LTX whose bit ordering is only assumed.
p3_build75_bus_nets $req_base 64
p3_build75_bus_nets $stall_base 64
p3_build75_bus_nets $count_base 9
p3_build75_scalar_net $trigger_name
p3_build75_bus_nets $pc_base 64
p3_build75_bus_nets $fu_base 4
p3_build75_bus_nets $op_base 8
p3_build75_scalar_net $valid_name
p3_build75_scalar_net $commit_ack_name
p3_build75_scalar_net $lsu_ready_name
p3_build75_scalar_net $lsu_commit_name

set clock_candidates [get_nets -quiet [list chipset_clk]]
if {[llength $clock_candidates] != 1} {
    puts "ERROR: Build 75 expected one chipset_clk net, found [llength $clock_candidates]"
    exit 1
}

set xdc_dir "${project_dir}/${project_name}.srcs/constrs_1/imports"
file mkdir $xdc_dir
set xdc_file "${xdc_dir}/p3_build75_debug.xdc"
set old_xdc [get_files -quiet $xdc_file]
if {[llength $old_xdc] != 0} {
    remove_files $old_xdc
}

set fh [open $xdc_file w]
puts $fh "# Generated by scripts/p3_build75_insert_debug.tcl"
puts $fh "create_debug_core u_ila_build75 ila"
puts $fh "set_property C_ADV_TRIGGER false \[get_debug_cores u_ila_build75\]"
puts $fh "set_property C_DATA_DEPTH 8192 \[get_debug_cores u_ila_build75\]"
puts $fh "set_property C_EN_STRG_QUAL true \[get_debug_cores u_ila_build75\]"
puts $fh "set_property C_INPUT_PIPE_STAGES 0 \[get_debug_cores u_ila_build75\]"
puts $fh "set_property C_NUM_OF_PROBES 11 \[get_debug_cores u_ila_build75\]"
puts $fh "connect_debug_port u_ila_build75/clk \[get_nets \[list {chipset_clk}\]\]"
p3_build75_write_probe $fh probe0 $trigger_name 1 1
p3_build75_write_probe $fh probe1 $count_base 9 0
p3_build75_write_probe $fh probe2 $req_base 64 0
p3_build75_write_probe $fh probe3 $stall_base 64 0
p3_build75_write_probe $fh probe4 $pc_base 64 0
p3_build75_write_probe $fh probe5 $valid_name 1 0
p3_build75_write_probe $fh probe6 $fu_base 4 0
p3_build75_write_probe $fh probe7 $op_base 8 0
p3_build75_write_probe $fh probe8 $commit_ack_name 1 0
p3_build75_write_probe $fh probe9 $lsu_ready_name 1 0
p3_build75_write_probe $fh probe10 $lsu_commit_name 1 0
close $fh

close_design
add_files -fileset constrs_1 -norecurse $xdc_file
set_property used_in_synthesis false [get_files $xdc_file]
set_property used_in_implementation true [get_files $xdc_file]
puts "Build 75 implementation-only debug XDC: ${xdc_file}"
