# p3_build90_insert_debug.tcl -- Post-synthesis diagnostic ILA for the
# clean-RTL TIME rebuild.  The implementation-only core observes commit PC,
# commit control, CSR address/exception state, privilege, mcounteren, and the
# cycle counter used to implement TIME.

if {![info exists project_dir] || ![info exists project_name]} {
    error "Build 90 hook requires project_dir and project_name"
}

set cva6 \
    {u_openpiton/system_inst/chip/tile0/g_ariane_core.core/ariane/i_cva6}
set scoreboard "${cva6}/issue_stage_i/i_scoreboard"
set commit_base "${scoreboard}/commit_instr_id_commit\[0\]"
set csr "${cva6}/csr_regfile_i"

proc p3_b90_require_one {kind objects label} {
    if {[llength $objects] != 1} {
        error "Build 90 expected one $kind for $label, found [llength $objects]"
    }
    return [lindex $objects 0]
}

proc p3_b90_net_name {candidates label} {
    set matches [list]
    foreach candidate $candidates {
        set matches [concat $matches [get_nets -quiet [list $candidate]]]
    }
    set net [p3_b90_require_one net [lsort -unique $matches] $label]
    return [get_property NAME $net]
}

proc p3_b90_bus_names {base width label} {
    set result [list]
    for {set bit 0} {$bit < $width} {incr bit} {
        lappend result [p3_b90_net_name [list "${base}\[${bit}\]"] \
            "${label} bit ${bit}"]
    }
    return $result
}

proc p3_b90_q_name {cell_name} {
    set cell [p3_b90_require_one cell \
        [get_cells -quiet [list $cell_name]] $cell_name]
    set qpin [p3_b90_require_one pin \
        [get_pins -quiet -of_objects $cell \
            -filter {DIRECTION == OUT && REF_PIN_NAME == Q}] \
        "${cell_name}/Q"]
    set net [p3_b90_require_one net [get_nets -quiet -of_objects $qpin] \
        "${cell_name}/Q net"]
    return [get_property NAME $net]
}

proc p3_b90_xdc_net_list {names} {
    set quoted [list]
    foreach name $names {
        lappend quoted "{${name}}"
    }
    return [join $quoted " "]
}

proc p3_b90_write_probe {fh index names trigger} {
    set port "probe${index}"
    if {$index != 0} {
        puts $fh "create_debug_port u_ila_build90 probe"
    }
    puts $fh "set_property port_width [llength $names] \
        \[get_debug_ports u_ila_build90/${port}\]"
    set probe_type [expr {$trigger ? "DATA_AND_TRIGGER" : "DATA"}]
    puts $fh "set_property PROBE_TYPE ${probe_type} \
        \[get_debug_ports u_ila_build90/${port}\]"
    puts $fh "connect_debug_port u_ila_build90/${port} \
        \[get_nets \[list [p3_b90_xdc_net_list $names]\]\]"
}

open_run synth_1

set commit_pc [p3_b90_bus_names "${commit_base}\[pc\]" 64 {commit PC}]
set commit_valid [p3_b90_net_name [list "${commit_base}\[valid\]"] \
    {commit valid}]
set commit_ack [p3_b90_net_name \
    [list "${scoreboard}/commit_ack\[0\]"] {commit ack}]
set commit_fu [p3_b90_bus_names "${commit_base}\[fu\]" 4 {commit FU}]
set commit_op [p3_b90_bus_names "${commit_base}\[op\]" 8 {commit op}]

set csr_addr [list]
for {set bit 0} {$bit < 12} {incr bit} {
    lappend csr_addr [p3_b90_net_name [list \
        "${cva6}/csr_addr_ex_csr\[${bit}\]" \
        "${cva6}/ex_stage_i/csr_buffer_i/csr_addr_ex_csr\[${bit}\]"] \
        "CSR address bit ${bit}"]
}
set csr_illegal [p3_b90_net_name \
    [list "${cva6}/csr_exception_csr_commit\[cause\]\[1\]"] \
    {CSR illegal flag}]
set priv [list \
    [p3_b90_q_name "${csr}/priv_lvl_q_reg\[0\]"] \
    [p3_b90_q_name "${csr}/priv_lvl_q_reg\[1\]"]]
set mcounteren [list]
for {set bit 0} {$bit < 6} {incr bit} {
    lappend mcounteren [p3_b90_q_name \
        "${csr}/mcounteren_q_reg\[${bit}\]"]
}
set cycle [list]
for {set bit 0} {$bit < 64} {incr bit} {
    lappend cycle [p3_b90_q_name "${csr}/cycle_q_reg\[${bit}\]"]
}

set clock [p3_b90_require_one net [get_nets -quiet [list chipset_clk]] \
    {chipset clock}]
set clock_name [get_property NAME $clock]

set xdc_dir "${project_dir}/${project_name}.srcs/constrs_1/imports"
file mkdir $xdc_dir
set xdc_file "${xdc_dir}/p3_build90_debug.xdc"
foreach old [get_files -quiet $xdc_file] {
    remove_files $old
}
set fh [open $xdc_file w]
puts $fh "# Generated by scripts/p3_build90_insert_debug.tcl"
puts $fh "create_debug_core u_ila_build90 ila"
puts $fh "set_property C_ADV_TRIGGER false \
    \[get_debug_cores u_ila_build90\]"
puts $fh "set_property C_DATA_DEPTH 4096 \
    \[get_debug_cores u_ila_build90\]"
puts $fh "set_property C_EN_STRG_QUAL false \
    \[get_debug_cores u_ila_build90\]"
puts $fh "set_property C_INPUT_PIPE_STAGES 0 \
    \[get_debug_cores u_ila_build90\]"
puts $fh "set_property C_NUM_OF_PROBES 10 \
    \[get_debug_cores u_ila_build90\]"
puts $fh "connect_debug_port u_ila_build90/clk \
    \[get_nets \[list {${clock_name}}\]\]"
p3_b90_write_probe $fh 0 $commit_pc 1
p3_b90_write_probe $fh 1 [list $commit_valid] 0
p3_b90_write_probe $fh 2 [list $commit_ack] 0
p3_b90_write_probe $fh 3 $commit_fu 0
p3_b90_write_probe $fh 4 $commit_op 0
p3_b90_write_probe $fh 5 $csr_addr 0
p3_b90_write_probe $fh 6 [list $csr_illegal] 0
p3_b90_write_probe $fh 7 $priv 0
p3_b90_write_probe $fh 8 $mcounteren 0
p3_b90_write_probe $fh 9 $cycle 0
close $fh

close_design
add_files -fileset constrs_1 -norecurse $xdc_file
set_property used_in_synthesis false [get_files $xdc_file]
set_property used_in_implementation true [get_files $xdc_file]
puts "Build 90 implementation-only TIME diagnostic XDC: $xdc_file"
