#!/usr/bin/env python3
import argparse
from pathlib import Path


def cpu_node(idx: int) -> str:
    return f"""        CPU{idx}: cpu@{idx} {{
            clock-frequency = <30000000>;
            u-boot,dm-pre-reloc;
            device_type = "cpu";
            reg = <{idx}>;
            status = "okay";
            compatible = "openhwgroup,cva6", "riscv";
            riscv,isa = "rv64imafdc";
            mmu-type = "riscv,sv39";
            tlb-split;
            CPU{idx}_intc: interrupt-controller {{
                #address-cells = <0>;
                #interrupt-cells = <1>;
                interrupt-controller;
                compatible = "riscv,cpu-intc";
            }};
        }};
"""


def interrupt_list(harts: int, supervisor: bool) -> str:
    parts = []
    for idx in range(harts):
        if supervisor:
            parts.append(f"&CPU{idx}_intc 11 &CPU{idx}_intc 9")
        else:
            parts.append(f"&CPU{idx}_intc 3 &CPU{idx}_intc 7")
    return " ".join(parts)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate the P3 OpenSBI/Linux DTB source for N harts."
    )
    parser.add_argument("--harts", type=int, default=64)
    parser.add_argument("--out", required=True)
    parser.add_argument(
        "--bootargs",
        default=(
            "earlycon=uart8250,mmio,0xfff0c2c000 "
            "console=ttyS0,115200n8 root=/dev/ram0 rw "
            "loglevel=8 keep_bootcon initcall_debug"
        ),
    )
    parser.add_argument("--plic-ndev", type=int, default=2)
    args = parser.parse_args()

    if args.harts < 1:
        raise SystemExit("--harts must be positive")

    cpus = "".join(cpu_node(idx) for idx in range(args.harts))
    clint_interrupts = interrupt_list(args.harts, supervisor=False)
    plic_interrupts = interrupt_list(args.harts, supervisor=True)

    dts = f"""// Generated by scripts/p3_generate_opensbi_dts.py
// P3 OpenSBI/Linux DTB source for {args.harts} harts.

/dts-v1/;

/ {{
    #address-cells = <2>;
    #size-cells = <2>;
    compatible = "openpiton,cva6platform";

    chosen {{
        stdout-path = "uart0:115200";
        bootargs = "{args.bootargs}";
    }};

    aliases {{
        console = &uart0;
        serial0 = &uart0;
    }};

    cpus {{
        #address-cells = <1>;
        #size-cells = <0>;
        timebase-frequency = <234375>;
{cpus}
    }};

    memory@80000000 {{
        device_type = "memory";
        reg = <0x00000000 0x80000000 0x00000000 0x80000000>;
    }};

    sdhci_0: sdhci@f000000000 {{
        status = "okay";
        compatible = "openpiton,piton-mmc";
        reg = <0x000000f0 0x00000000 0x0000000f 0xf0300000>;
    }};

    uart0: uart@fff0c2c000 {{
        compatible = "ns16550";
        reg = <0x000000ff 0xf0c2c000 0x00000000 0x000d4000>;
        clock-frequency = <30000000>;
        current-speed = <115200>;
        interrupt-parent = <&PLIC0>;
        interrupts = <1>;
        reg-shift = <0>;
    }};

    clint@fff1020000 {{
        compatible = "sifive,clint0", "riscv,clint0";
        interrupts-extended = <{clint_interrupts}>;
        reg = <0x000000ff 0xf1020000 0x00000000 0x000c0000>;
        reg-names = "control";
    }};

    PLIC0: plic@fff1100000 {{
        #address-cells = <0>;
        #interrupt-cells = <1>;
        compatible = "sifive,plic-1.0.0", "riscv,plic0";
        interrupt-controller;
        interrupts-extended = <{plic_interrupts}>;
        reg = <0x000000ff 0xf1100000 0x00000000 0x04000000>;
        riscv,max-priority = <7>;
        riscv,ndev = <{args.plic_ndev}>;
    }};
}};
"""

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(dts, encoding="ascii")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
